<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Message extends Model
{
    use HasFactory;

    protected $fillable = ['conversation_id', 'sender_id', 'body', 'attachment', 'read_at'];

    protected $casts = ['read_at' => 'datetime'];

    /**
     * Always append attachment_url so the frontend receives a ready-to-use URL
     * without needing to know the storage driver or path convention.
     */
    protected $appends = ['attachment_url'];

    // ── Relationships ─────────────────────────────────────────────────────────

    public function conversation()
    {
        return $this->belongsTo(Conversation::class);
    }

    public function sender()
    {
        return $this->belongsTo(User::class, 'sender_id');
    }

    // ── Accessors ─────────────────────────────────────────────────────────────

    /**
     * Returns a publicly accessible URL for the attachment, or null if none.
     * Ensures XSS safety: the URL is generated by Storage, not from raw user input.
     */
    public function getAttachmentUrlAttribute(): ?string
    {
        return $this->attachment ? Storage::url($this->attachment) : null;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    public function markRead(): void
    {
        if (!$this->read_at) {
            $this->update(['read_at' => now()]);
        }
    }
}
